getwd()
setwd("/Users/Natsume/Documents/1learnD3/d3-template/")
dir()
hkws <- read.csv("hkws.csv")
?read.csv # check use of different parameters 
hkws <- read.csv("hkws.csv", header=F)
library(dplyr)
hkws %>% head()
colnames(hkws) <- c("Date", "Open", "High", "Low", "Close", "Volume", "Cash")
write.csv(hkws, file = "/Users/Natsume/Documents/1learnD3/d3-template/hkwsName.csv")
